version: '3.8'
services:
  stats-server:
    build: ./stat-service/stat-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
     - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmStatDb?user=postgres&password=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
          - POSTGRES_DB=ewmStatDb
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=root


