DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id        bigint generated by default as identity not null,

    app       VARCHAR(128)                             NOT NULL,
    uri       VARCHAR(512)                             NOT NULL,
    ip        VARCHAR(128)                             NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE             NOT NULL
);