DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id        bigint generated by default as identity not null,

    app       VARCHAR(16)                             NOT NULL,
    uri       VARCHAR(64)                             NOT NULL,
    ip        VARCHAR(16)                             NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE             NOT NULL
);